#!/usr/bin/env python3
"""Regenerate docs/ENDPOINTS.md from the OpenAPI schema.

Run from the project root after adding or changing routes:

    .venv/bin/python -m scripts.gen_endpoints_doc

The interactive Swagger UI at /docs remains the source of truth; this produces a
static, browsable snapshot for the repo so the endpoint list can be read without
hitting the API.
"""

from pathlib import Path

from app.main import app

HEADER = [
    "# DataGod — API Endpoints",
    "",
    "> Generated by `scripts/gen_endpoints_doc.py` from the OpenAPI schema.",
    "> The interactive, always-current version is the **Swagger UI at `/docs`** (HTTP Basic auth).",
    "> Every endpoint requires the `X-API-Key` header except `GET /health`.",
    "",
]

_HTTP_METHODS = ("get", "post", "put", "delete", "patch")


def render() -> str:
    schema = app.openapi()
    tags = schema.get("tags", [])
    order = [tag["name"] for tag in tags]
    descriptions = {tag["name"]: tag.get("description", "") for tag in tags}

    grouped: dict[str, list[tuple[str, str, str]]] = {}
    for path, operations in schema["paths"].items():
        for method, operation in operations.items():
            if method not in _HTTP_METHODS:
                continue
            tag = (operation.get("tags") or ["(untagged)"])[0]
            grouped.setdefault(tag, []).append(
                (method.upper(), path, operation.get("summary", ""))
            )

    total = sum(len(rows) for rows in grouped.values())
    lines = list(HEADER)
    lines.append(
        f"**{total} endpoints across {len(grouped)} groups.** "
        "Base URL: `https://datagod.example.com`"
    )
    lines.append("")

    for tag in order:
        rows = grouped.get(tag)
        if not rows:
            continue
        lines.append(f"## {tag}")
        if descriptions.get(tag):
            lines += ["", descriptions[tag]]
        lines += ["", "| Method | Path | Summary |", "|--------|------|---------|"]
        for method, path, summary in sorted(rows, key=lambda row: row[1]):
            lines.append(f"| {method} | `{path}` | {summary} |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    out = Path(__file__).parent.parent / "docs" / "ENDPOINTS.md"
    out.write_text(render())
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
